/**
 * FIGHTCORE domain model.
 *
 * Mirrors the relational schema in db/schema.sql. Every entity that carries
 * facts declares its provenance so the UI can always say where a number comes from.
 */

export type Provenance = "official" | "imported" | "calculated" | "editorial" | "demo";

export type ISODate = string; // YYYY-MM-DD

export type Sex = "M" | "F";

export interface Country {
  code: string; // ISO 3166-1 alpha-3
  name: string; // Spanish display name
  lat: number;
  lon: number;
}

export interface Division {
  id: string;
  slug: string;
  name: string;
  short: string;
  sex: Sex;
  limitLb: number;
  limitKg: number;
  order: number;
}

export type OrgStatus = "active" | "defunct" | "absorbed";

export interface Organization {
  id: string;
  slug: string;
  name: string;
  short: string;
  country: string | null;
  region: string;
  /** Year of first event, when known with confidence. */
  activeFrom: number | null;
  activeTo: number | null;
  status: OrgStatus;
  group: "major" | "europe" | "historical";
  note: string | null;
  provenance: Provenance;
}

export type Stance = "Orthodox" | "Southpaw" | "Switch";
export type FighterStatus = "active" | "inactive" | "retired";

export interface Fighter {
  id: string;
  slug: string;
  firstName: string;
  lastName: string;
  nickname: string | null;
  /** ISO 3166-1 alpha-3, or null when no source states it. */
  country: string | null;
  sex: Sex;
  birthDate: ISODate | null;
  heightCm: number | null;
  reachCm: number | null;
  stance: Stance | null;
  divisionId: string;
  orgId: string;
  status: FighterStatus;
  /** Professional record outside FIGHTCORE coverage; null when unknown. */
  priorRecord: { w: number; l: number; d: number } | null;
  /** Place of birth (Wikidata), city label and ISO-3 country. */
  birthPlace?: { city: string; country: string | null } | null;
  /** Gym / team and base fighting style, when a source states them. */
  team?: string | null;
  style?: string | null;
  /** Wikidata entity (Q-id) when the fighter was matched to it. */
  wikidata?: string | null;
  photo: FighterPhoto;
  provenance: Provenance;
}

/**
 * Portrait shown for a fighter. "illustration" = generated by FIGHTCORE (demo
 * fighters are fictional); "licensed" = photograph under a free licence, always
 * shown with author and licence; "official" = UFC athlete photo (© UFC, only
 * when PHOTO_SOURCE allows it); "none" = no photo, the UI shows initials.
 */
export interface FighterPhoto {
  src: string;
  kind: "illustration" | "licensed" | "official" | "none";
  credit: string;
  updated: ISODate;
  author?: string;
  license?: string;
  licenseUrl?: string | null;
  sourceUrl?: string;
}

export type Method = "KO/TKO" | "SUB" | "U-DEC" | "S-DEC" | "M-DEC" | "DQ" | "DRAW" | "NC";
export type Outcome = "W" | "L" | "D" | "NC";

export interface StrikeStats {
  sigLanded: number;
  sigAttempted: number;
  totalLanded: number;
  totalAttempted: number;
  head: number;
  body: number;
  leg: number;
  distance: number;
  clinch: number;
  ground: number;
  kd: number;
  tdLanded: number;
  tdAttempted: number;
  subAttempts: number;
  ctrlSec: number;
}

export interface RoundStats {
  round: number;
  red: Pick<StrikeStats, "sigLanded" | "sigAttempted" | "tdLanded" | "ctrlSec" | "kd">;
  blue: Pick<StrikeStats, "sigLanded" | "sigAttempted" | "tdLanded" | "ctrlSec" | "kd">;
}

export type FightStatus = "completed" | "scheduled";

export interface Fight {
  id: string;
  eventId: string;
  date: ISODate;
  orgId: string;
  divisionId: string;
  redId: string;
  blueId: string;
  status: FightStatus;
  winnerId: string | null;
  method: Method | null;
  submission: string | null;
  round: number | null;
  /** Seconds elapsed in the final round. */
  time: number | null;
  scheduledRounds: number;
  titleFight: boolean;
  /** Interim title (only meaningful when titleFight). */
  interim?: boolean;
  referee?: string | null;
  slot: "main" | "co-main" | "main-card" | "prelims";
  order: number;
  red: StrikeStats | null;
  blue: StrikeStats | null;
  rounds: RoundStats[];
  /** Judges' round tallies for decisions (red-blue), e.g. "29-28". */
  scorecards: string[] | null;
  /** Results-based strength (Elo) before the fight — input to opponent quality. */
  redStrengthPre: number;
  blueStrengthPre: number;
  provenance: Provenance;
}

export interface Event {
  id: string;
  slug: string;
  name: string;
  orgId: string;
  date: ISODate;
  city: string;
  country: string;
  venue: string | null;
  status: "completed" | "upcoming";
  fightIds: string[];
  provenance: Provenance;
}

export interface Championship {
  orgId: string;
  divisionId: string;
  fighterId: string;
  wonFightId: string;
  from: ISODate;
  to: ISODate | null;
  defenses: number;
  interim?: boolean;
  /** The source doesn't record how the reign ended: `to` is the holder's last bout there. */
  toApprox?: boolean;
}

export interface HistoricalEvent {
  year: number;
  date: ISODate | null;
  title: string;
  body: string;
  orgId: string | null;
  kind: "founding" | "rules" | "milestone" | "business";
  provenance: Provenance;
}

/** Fight seen from one fighter's side. Computed, not stored. */
export interface FighterBout {
  fight: Fight;
  event: Event;
  corner: "red" | "blue";
  opponentId: string;
  outcome: Outcome | null;
  own: StrikeStats | null;
  opp: StrikeStats | null;
  ownStrengthPre: number;
  oppStrengthPre: number;
}
